feat: Extensions
aip-dev/site-generator pull request #3
Opened 2020-07-15 02:37 UTC by lukesneeringer

This adds a basic extension system. How it works is thus:

Basic Markdown files work like they always have. However, the system does some dark magic under the hood and makes any Markdown (level 2 or 3) header into a block. So...

```md
## Foo bar baz

Lorem ipsum dolor set amet
```

Becomes...

```md
{% block foo_bar_baz %}
## Foo bar baz

Lorem ipsum dolor set amet
{% endblock %}
```

That allows an overriding template to extend the original one and override sections:

```md
{% extends aip.templates.generic %}

{% block foo_bar_baz %}
## My mo-betta foo bar baz

Lorem ipsum dolor set something-not-amet
{% endblock %}
```

A limitation is that one can only override _entire sections_: I expect we will have other overrides to come, but I expect how we deal with them is by having other override mechanisms (there will be no single one-size-fits-all variant), and this still gives all the power that the old split-file system does.

2020-07-19 19:14 UTC, mkistler commented on aip_site/models/scope.py
> +                        continue
I'm curious why you did not just filter the list to just '.md' and '.md.j2' files above with list comprehension.

2020-07-19 19:32 UTC, mkistler commented on aip_site/models/scope.py
> +                            contents = '\n'.join(segments)
I'm struggling to understand why this works.  If we first split the content at level-3 headers -- ignoring level-2 headers -- then it seems that we could get level-3 blocks that include level-2 headers.

For example, with the content:
```
## foo

lorem ipsum

### bar

dolor sit amet

## baz

consectetur adipiscing elit

### qux

sed do eiusmod
```

I think the first `seg` will be
```
bar

dolor sit amet

## baz

consectetur adipiscing elit

```

and I don't think that's what you want.

What I think you need to do is first split on level-2 heads, and then on each of these segments split on level 3 heads.

And of course all this assumes that there's only one level 1 head at the top, otherwise you need to add a outer layer of looping over level-1 segments.

2020-07-19 19:38 UTC, mkistler requested changes
I left a few questions/comments, and I think you should update the README.md with an explanation of this logic -- basically add the content of the PR description to the README.

2020-07-20 14:29 UTC, lukesneeringer commented on aip_site/models/scope.py
> +                            contents = '\n'.join(segments)
> What I think you need to do is first split on level-2 heads, and then on each of these segments split on level 3 heads.

You know what, I think this is probably right. I thought a lot about making nesting work correctly but not about this case, and I believe you are correct that the logic would not work.

2020-07-23 18:25 UTC, lukesneeringer commented on aip_site/models/scope.py
> +                        continue
No particular reason, although I think the `sorted` call is doing enough that I think I would prefer not pack more logic there.

2020-07-23 20:59 UTC, lukesneeringer commented on aip_site/models/scope.py
> +                            contents = '\n'.join(segments)
@mkistler Thanks for pointing this out. After thinking about it more, I refactored this significantly to have the Markdown TOC plugin do most of the heavy lifting, which I expect will be significantly less error-prone.

2020-08-09 22:34 UTC, mkistler approved these changes
Looks good! 👍

2020-08-10 20:58 UTC, merged

2024-09-25 17:28 UTC, UglyJoevIne approved these changes